sudo: required
dist: trusty

language: go

go:
  - "1.10.x"

git:
    submodules: false

addons:
  apt:
    packages:
      - go-dep

before_install:
  - dep ensure -update

before_script:
  - make format
  - make vet

script:
  - make travis

after_success:
  - bash <(curl -s https://codecov.io/bash)
